_BASE_: semask_maskformer2_R50_bs16_160k.yaml
MODEL:
  BACKBONE:
    NAME: "D2SeMaskSwinTransformer"
  SWIN:
    EMBED_DIM: 192
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [6, 12, 24, 48]
    WINDOW_SIZE: 12
    SEM_WINDOW_SIZE: 12
    NUM_SEM_BLOCKS: 1
    APE: False
    DROP_PATH_RATE: 0.3
    PATCH_NORM: True
    PRETRAIN_IMG_SIZE: 384
  WEIGHTS: "./pretrained/semask_large_mask2former_msfapn_ade20k.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
DATASETS:
  TRAIN: ("trash_recycle_sem_seg_v2_train_1",)
  TEST: ("trash_recycle_sem_seg_v2_val_1",)
INPUT:
  MIN_SIZE_TRAIN: !!python/object/apply:eval ["[int(x * 0.1 * 640) for x in range(5, 21)]"]
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 512
  MAX_SIZE_TRAIN: 1280
  MAX_SIZE_TEST: 1280
  CROP:
    ENABLED: False
    TYPE: "absolute"
    SIZE: (512, 512)
    SINGLE_CATEGORY_MAX_AREA: 1.0
  COLOR_AUG_SSD: True
  SIZE_DIVISIBILITY: 512  # used in dataset mapper
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 650
  AUG:
    ENABLED: False
    MIN_SIZES: [320, 480, 640, 800, 960, 1120]
    MAX_SIZE: 2240
    FLIP: True
SOLVER:
    BEST_CHECKPOINTER:
        ENABLED: True
        TYPE: "sem_seg"
        METRIC: "mIoU"
    CHECKPOINT_PERIOD: 650
OUTPUT_DIR: "./trash_dataV1_check_best_mIoU"